syms x z y
%eqn = 64 * Y * x^2 * z^2 * (Y + x^2 + z^2) + (-4*Y^2 + (4i)*Y*u - 4*Y*x^2 - 4*Y*z^2 + u^2 + (4i) * u * x^2 + 4 * x^2 * z^2)^2 == 0;
%solve(eqn, Y)
int( x^2 / (sqrt(x^2 + y^2 + z^2))^3 , x)
%simplify((-2i) * ( x * ( x + sqrt( x^2 + z^2 + Y ) ) + Y ) +...
%    sqrt( ( x + sqrt( x^2 + z^2 + Y ) )^2 * ( 4 * x^2 + 4 * Y ) - ( 2 * x * ( x + sqrt( x^2 + z^2 + Y ) ) + 2 * Y )^2 ))
% simplify(...
%            (1/48) * (...
%                      (-3) * a^3 * log( 2 * ( sqrt( x * (a + x) + b ) + x ) + a ) +...
%                      6  * a^2 * sqrt( x * (a + x) + b ) -...
%                      48 * (sqrt(b))^3 *...
%                      log...
%                      (...
%                       2 * sqrt(b) * sqrt( x * (a + x) + b ) +...
%                       a*x + 2*b...
%                      ) +...
%                      16 * x^2 * sqrt( x * (a + x) + b ) +...
%                      28 * a*x * sqrt( x * (a + x) + b ) +...
%                      64 * b * sqrt( x * (a + x) + b ) +...
%                      36 * a*b * log( 2 * ( sqrt( x * (a + x) + b ) + x ) + a ) +...
%                      48 * (sqrt(b))^3 * log( x * (sqrt(b))^5 )...
%                     )...
% )
